### PR TITLE
Bug/#62 fix parsing either statement

### LINKED ISSUE #62: The 'either' statement is incorrectly parsed via cfg
I am currently testing this holiday library, and I configured US Independence Day like this:

```
holiday either  JUL  4 or if SUN then fixed JUL 5         Independence Day
holiday either  JUL  4 or if Sat then fixed JUL 3         Independence Day
```

However, the result for Year 2026 Jul 4 is mis-parsed as Jul 5. (Jul 3 is expected).

I debugged into the code, and found this place has an issue:

HolidayMatcher.java
```
	public ConditionBuilder createConditionBuilder(Matcher matcher) {
		return new ConditionBuilder()
				.withDaysOfWeek(daysOfWeek(matcher.group(Patterns.PIVOT_DAYS_OF_WEEK_GROUP)))
				.withPivotDate(monthDay(
						matcher.group(Patterns.**MONTH_GROUP_2**), matcher.group(Patterns.**DAY_GROUP_2**)));
	}
```

In this code, the matcher should use Patterns.**MONTH_GROUP** and Patterns.**DAY_GROUP** instread.

Kindly check or if I can fix with a pull request?

Thanks

### PR DESCRIPTION
**Pull request by ckunki**
Closes #62

### CODE REVIEW

File: src/main/java/org/itsallcode/holidays/calculator/logic/Easter.java [hunk 1]
```diff
@@ -19,6 +19,10 @@
 
 import java.time.LocalDate;
 
+/**
+ * This class provides calculation methods for the data of the Easter feast and
```
Comment (kaklakariada) [inline src/main/java/org/itsallcode/holidays/calculator/logic/Easter.java]:
```suggestion
 * This class provides calculation methods for the date of the Easter feast and
```

File: src/main/java/org/itsallcode/holidays/calculator/logic/Formatter.java [hunk 2]
```diff
@@ -54,24 +88,47 @@ public static String format(MonthDay monthDay, Day dayInterpretation) {
 		}
 	}
 
+	/**
+	 * Return string specifying the offset in days in human readable form. If
+	 * {@code offset == 0} return an empty string.
+	 *
+	 * @param offset offset in days
+	 * @return string specifying the offset in human readable form. negative values
```
Comment (kaklakariada) [inline src/main/java/org/itsallcode/holidays/calculator/logic/Formatter.java]:
```suggestion
	 * @return string specifying the offset in human readable form. Negative values
```

File: src/main/java/org/itsallcode/holidays/calculator/logic/Formatter.java [hunk 3]
```diff
@@ -54,24 +88,47 @@ public static String format(MonthDay monthDay, Day dayInterpretation) {
...
+	 * @param offset offset in days
+	 * @return string specifying the offset in human readable form
+	 */
 	public static String offsetWithoutZero(int offset) {
 		return (offset == 0 ? "" : offset(offset) + " ");
 	}
 
+	/**
+	 * Return a string representing the ordinal variant of the given integer
+	 * {@code offset}. E.g. 1 becomes "first, 2 becomes "2nd", etc.
```
Comment (kaklakariada) [inline src/main/java/org/itsallcode/holidays/calculator/logic/Formatter.java]:
```suggestion
	 * Return a string representing the ordinal variant of the given integer
	 * {@code offset}. E.g. 1 becomes "1st", 2 becomes "2nd", etc.
```

File: src/main/java/org/itsallcode/holidays/calculator/logic/conditions/NegatedCondition.java [hunk 4]
```diff
@@ -18,11 +18,26 @@
 package org.itsallcode.holidays.calculator.logic.conditions;
 
 import java.time.Year;
+import java.util.Objects;
 
+/**
+ * Negated variant of the initial condition.
+ *
+ * Whenever the initial condition is {@code true} the negated condition will
+ * {@code false} and vice-versa.
```
Comment (kaklakariada) [inline src/main/java/org/itsallcode/holidays/calculator/logic/conditions/NegatedCondition.java]:
```suggestion
 * Whenever the initial condition is {@code true} the negated condition will be
 * {@code false} and vice-versa.
```

File: src/main/java/org/itsallcode/holidays/calculator/logic/conditions/NegatedCondition.java [hunk 5]
```diff
@@ -18,11 +18,26 @@
...
+ */
 public class NegatedCondition extends Condition {
 
 	private final Condition other;
 
+	/**
+	 * Create a condition negating the initial condition in parameter {@code other}.
+	 *
+	 * Whenever the initial condition is {@code true} the negated condition will
+	 * {@code false} and vice-versa.
```
Comment (kaklakariada) [inline src/main/java/org/itsallcode/holidays/calculator/logic/conditions/NegatedCondition.java]:
```suggestion
	 * Whenever the initial condition is {@code true} the negated condition will be
	 * {@code false} and vice-versa.
```

File: src/main/java/org/itsallcode/holidays/calculator/logic/conditions/builder/ConditionBuilder.java [hunk 6]
```diff
@@ -43,23 +63,54 @@ public Condition build() {
...
+	 */
 	public ConditionBuilder withOptionalPivotDateFrom(Holiday holiday) {
 		if (pivotDate == null) {
 			this.pivotDate = holiday.getMonthDay();
 		}
 		return this;
 	}
 
+	/**
+	 * Add a specification to the builder to negate the condition the is specified
```
Comment (kaklakariada) [inline src/main/java/org/itsallcode/holidays/calculator/logic/conditions/builder/ConditionBuilder.java]:
```suggestion
	 * Add a specification to the builder to negate the condition that is specified
```

File: src/main/java/org/itsallcode/holidays/calculator/logic/parser/AbbreviationParser.java [hunk 7]
```diff
@@ -19,19 +19,43 @@
...
+ * This class enables to parse enum values from potentially abbreviated strings.
+ *
+ * @param <T> Enum class containing the values to be parsed from the string.
+ */
 public class AbbreviationParser<T extends Enum<T>> {
 
+	/**
+	 * Excepting indicating an ambiguous abbreviation for a the name of a month or
+	 * day of the week, e.g. "T" for the day of the week that could either mean
+	 * "Tuesday" or "Thursday".
```
Comment (kaklakariada) [inline src/main/java/org/itsallcode/holidays/calculator/logic/parser/AbbreviationParser.java]:
```suggestion
	 * Exception indicating an ambiguous abbreviation for the name of a month or
	 * day of the week, e.g. "T" for the day of the week that could either mean
	 * "Tuesday" or "Thursday".
```

File: src/main/java/org/itsallcode/holidays/calculator/logic/parser/AbbreviationParser.java [hunk 8]
```diff
@@ -19,19 +19,43 @@
...
+		 * @param message message of the exception
+		 */
 		public AmbigueAbbreviationException(String message) {
 			super(message);
 		}
 	}
 
+	/**
+	 * Excepting indicating an illegal abbreviation for a the name of a month or day
+	 * of the week. E.g. "D" for a day of the week.
```
Comment (kaklakariada) [inline src/main/java/org/itsallcode/holidays/calculator/logic/parser/AbbreviationParser.java]:
```suggestion
	 * Exception indicating an illegal abbreviation for a the name of a month or day
	 * of the week. E.g. "D" for a day of the week.
```

File: src/main/java/org/itsallcode/holidays/calculator/logic/parser/AbbreviationParser.java [hunk 9]
```diff
@@ -40,10 +64,21 @@ public InvalidAbbreviationException(String message) {
 	private final Class<T> clazz;
 	private final HashMap<String, T> cache = new HashMap<>();
 
+	/**
+	 * Create a new instance for the specified class.
+	 *
+	 * @param clazz class to create the abbreviation parser for
```
Comment (kaklakariada) [inline src/main/java/org/itsallcode/holidays/calculator/logic/parser/AbbreviationParser.java]:
```suggestion
	 * Create a new instance for the specified enum class.
	 *
	 * @param clazz enum class to create the abbreviation parser for
```

File: src/main/java/org/itsallcode/holidays/calculator/logic/parser/AbbreviationParser.java [hunk 10]
```diff
@@ -40,10 +64,21 @@ public InvalidAbbreviationException(String message) {
...
+	 */
 	public AbbreviationParser(Class<T> clazz) {
 		this.clazz = clazz;
 	}
 
+	/**
+	 * Return an enum for the specified prefix (e.g. abbreviation).
```
Comment (kaklakariada) [inline src/main/java/org/itsallcode/holidays/calculator/logic/parser/AbbreviationParser.java]:
```suggestion
	 * Return an enum value for the specified prefix (e.g. abbreviation).
```

File: src/main/java/org/itsallcode/holidays/calculator/logic/parser/HolidaysFileParser.java [hunk 11]
```diff
@@ -29,13 +29,21 @@
...
+/**
+ * Parser for a file containing holiday definitions.
+ */
 public class HolidaysFileParser {
 
+	/**
+	 * Represents an error that has occurred during parsing the holidays.
+	 */
 	public static class Error {
+		/** number of the line causing the error. */
```
Comment (kaklakariada) [inline src/main/java/org/itsallcode/holidays/calculator/logic/parser/HolidaysFileParser.java]:
```suggestion
		/** Number of the line causing the error. */
```

File: src/main/java/org/itsallcode/holidays/calculator/logic/parser/Token.java [hunk 12]
```diff
@@ -39,14 +59,28 @@ public static Pattern buildRegexp(final Object... elements) {
 		return Pattern.compile(sb.toString(), Pattern.CASE_INSENSITIVE);
 	}
 
+	/** name of the token's regex group */
 	public final String groupName;
+	/** regex pattern to match the token */
 	public final String pattern;
```
Comment (kaklakariada) [inline src/main/java/org/itsallcode/holidays/calculator/logic/parser/Token.java]:
```suggestion
	/** Name of the token's regex group */
	public final String groupName;
	/** Regex pattern to match the token */
	public final String pattern;
```

File: src/main/java/org/itsallcode/holidays/calculator/logic/parser/Token.java [hunk 13]
```diff
@@ -39,14 +59,28 @@ public static Pattern buildRegexp(final Object... elements) {
...
 
+	/**
+	 * Each token is represented as a named-group in the return regular expression.
+	 * This way you can the token's match data by specifying its group-name.
```
Comment (kaklakariada) [inline src/main/java/org/itsallcode/holidays/calculator/logic/parser/Token.java]:
```suggestion
	 * Each token is represented as a named-group in the returned regular expression.
	 * This way you can get the token's match data by specifying its group-name.
```
:question:

File: src/main/java/org/itsallcode/holidays/calculator/logic/variants/FloatingHoliday.java [hunk 14]
```diff
@@ -21,22 +21,48 @@
...
 		}
 	}
 
+	/**
+	 * Enables to refer to specific days in a month using colloquial phrases like
+	 * "first" or "last day of the month".
+	 */
 	public enum Day {
+		/**
+		 * format the number of the day of month as specified, i.e. in a numeric way.
```
Comment (kaklakariada) [inline src/main/java/org/itsallcode/holidays/calculator/logic/variants/FloatingHoliday.java]:
```suggestion
		 * Format the number of the day of month as specified, i.e. in a numeric way.
```

File: src/main/java/org/itsallcode/holidays/calculator/logic/variants/FloatingHoliday.java [hunk 15]
```diff
@@ -21,22 +21,48 @@
...
+		 */
 		AS_SPECIFIED,
+		/** use the first day of the month */
 		FIRST,
+		/** replace the number of the day of the month by "last-day" */
```
Comment (kaklakariada) [inline src/main/java/org/itsallcode/holidays/calculator/logic/variants/FloatingHoliday.java]:
```suggestion
		/** Use the first day of the month */
		FIRST,
		/** Replace the number of the day of the month by "last-day" */
```

File: src/main/java/org/itsallcode/holidays/calculator/logic/variants/FloatingHoliday.java [hunk 16]
```diff
@@ -21,22 +21,48 @@
...
+	 * Indicates the direction of an offset for the floating holiday from a specific
+	 * pivot date.
+	 */
 	public enum Direction {
-		BEFORE, AFTER;
-
+		/** the floating day is after the pivot date */
+		BEFORE,
+		/** the floating day is before the pivot date */
+		AFTER;
```
Comment (kaklakariada) [inline src/main/java/org/itsallcode/holidays/calculator/logic/variants/FloatingHoliday.java]:
```suggestion
		/** The floating day is after the pivot date. */
		BEFORE,
		/** The floating day is before the pivot date. */
		AFTER;
```

**Review by kaklakariada — CHANGES_REQUESTED** [review]

**Review by kaklakariada — CHANGES_REQUESTED** [review]
Looks good, that was a lot of work :+1:

**Review by kaklakariada — APPROVED** [review]
